### ISSUE TITLE
Wrong ExecStop command in Systemd template

### ISSUE THREAD

**Issue by Arledrian** [voxpupuli/puppet-redis#234]
Hi,

If i stop an instance (systemctl stop ...) i get an error because 'redis-server' doesn't support the '-p' option:
```
7198:C 17 Aug 19:47:07.942 # Fatal error, can't open config file '-p'
```

Maybe 'redis-cli' should be used instead of 'redis-server' for shutdown purpose.

[redis.service.erb.patch.txt](https://github.com/arioch/puppet-redis/files/1232161/redis.service.erb.patch.txt)

**Comment by bostrowski13** [comment]
i have the fix for this in https://github.com/arioch/puppet-redis/pull/230

**Comment by ekohl** [comment]
Which OS and Redis version was this on?

**Comment by pyslarvt** [comment]
I confirm this bug on Ubuntu 16.04 and Redis 5.0.7. Why not to use the ExecStop command like in the unit-file from the deb package?
```
ExecStop=/bin/kill -s TERM $MAINPID
```

**Comment by ekohl** [comment]
I'd like to utilize the shipped `redis@.service` (since Debian 10 and Ubuntu 18.04) since they contain many more improvements. However, right now I have no use case for multi instances and for the default service the package service file should be used so I have no time to work on this. PRs are welcome though.
